version: '3'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 5000:5000
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: app.py
    depends_on:
      - db
    networks:
      - app_network
    volumes:
      - .:/app
  
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flask_app_db
    volumes:
      - db_data:/var/lib/postgres/data
    networks:
      - app_network
    
  adminer:
    image: adminer
    ports:
      - "9090:8080"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
  
volumes:
  db_data: {}